# Generated by Django 3.2.25 on 2024-04-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240424_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='Rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories_serve',
            field=models.IntegerField(null=True, verbose_name='Calories/Serve'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Difficulty'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=2, verbose_name='Serves'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
