# Generated by Django 3.2.25 on 2024-04-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240425_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(max_length=15, null=True, verbose_name='Units'),
        ),
    ]
